# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/https://github.com/mochaccin/proyecto-datos.git',
                'doc_host': 'https://mochacchin.github.io',
                'git_url': 'https://github.com/mochacchin/https://github.com/mochaccin/proyecto-datos.git',
                'lib_path': 'https://github.com/mochaccin/proyecto_datos.git'},
  'syms': {'proyecto_datos.git.core': {'proyecto_datos.git.core.foo': ('core.html#foo', 'proyecto_datos.git/core.py')}}}
